app = 'binance-p2p-bot-aged-meadowlark-5171'
primary_region = 'iad'

[build]

[env]
  CRYPTO = 'USDT'
  FIAT = 'USD'
  MAX_PRICE = '1.09'
  POLL_INTERVAL = '60'

[checks]
  [checks.restart]
    grace_period = "5s"
    interval = "30s"
    method = "none"
    timeout = "5s"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
