app = 'binance-p2p-bot-aged-meadowlark-5171'
primary_region = 'iad'

[build]

[env]
  CRYPTO = 'USDT'
  FIAT = 'USD'
  MAX_PRICE = '1.09'
  POLL_INTERVAL = '60'

[http_service]
  internal_port = 8080
  auto_stop_machines = "off"
  auto_start_machines = true
  force_https = true

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
