services:
  - type: worker
    name: binance-p2p-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CRYPTO
        value: USDT
      - key: FIAT
        value: USD
      - key: MAX_PRICE
        value: "1.09"
      - key: PAYMENT_METHODS
        value: "Facebank"
      - key: POLL_INTERVAL
        value: "60"
